spring:
  datasource:
    url: jdbc:mysql://114.55.249.85:3306/employee_date
    username: root
    password: Zstu2018@
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql:true
server:
  port: 8181


